import type { Metadata } from "next";
import { Manrope,  } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "@/Component/Home/Navbar/ResponsiveNav";


const manrope = Manrope({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-manrope", // optional
});

export const metadata: Metadata = {
  title: "Startup File",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.className} antialiased h-600 bg-white`}>
        <ResponsiveNav />
        {children}
        {/* <Footer /> */}
        {/* <TopScroll /> */}
      </body>
    </html>
  );
}
